"""
CNAME Configuration Update Script for NextSlot Custom Domains
Updates CNAME records for service provider domains to point to Cloudflare
"""

import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'booking_saas.settings')
django.setup()

from providers.models import ServiceProvider

def update_cname_records():
    """Update CNAME records for all service providers"""
    
    # Cloudflare configuration
    CLOUDFLARE_CNAME_TARGET = "customers.nextslot.in"  # UPDATED CNAME TARGET
    TXT_RECORD_NAME = "_acme-challenge"
    
    print("\n" + "="*70)
    print("CNAME CONFIGURATION UPDATE FOR SERVICE PROVIDERS")
    print("="*70 + "\n")
    
    # Get all providers with custom domains
    providers_with_domains = ServiceProvider.objects.filter(
        custom_domain__isnull=False
    ).exclude(custom_domain='')
    
    if not providers_with_domains.exists():
        print("✗ No providers with custom domains found")
        return
    
    print(f"Found {providers_with_domains.count()} provider(s) with custom domains\n")
    
    for provider in providers_with_domains:
        print(f"Provider: {provider.name}")
        print(f"Custom Domain: {provider.custom_domain}")
        print(f"Domain Type: {provider.custom_domain_type}")
        print(f"Domain Verified: {provider.domain_verified}")
        print(f"SSL Enabled: {provider.ssl_enabled}")
        print("\n📋 REQUIRED DNS RECORDS:")
        print("-" * 70)
        
        # CNAME Record
        print(f"\n1️⃣  CNAME RECORD:")
        print(f"   Name/Host: {provider.custom_domain}")
        print(f"   Type: CNAME")
        print(f"   Value/Target: {CLOUDFLARE_CNAME_TARGET}")
        print(f"   TTL: 3600 (Auto)")
        
        # TXT Record for SSL verification
        print(f"\n2️⃣  TXT RECORD (For SSL Validation):")
        print(f"   Name: {TXT_RECORD_NAME}.{provider.custom_domain}")
        print(f"   Type: TXT")
        print(f"   Value: (Auto-generated by Cloudflare - will appear in your Cloudflare dashboard)")
        print(f"   TTL: 3600")
        
        # Update provider CNAME target
        if provider.cname_target != CLOUDFLARE_CNAME_TARGET:
            provider.cname_target = CLOUDFLARE_CNAME_TARGET
            provider.txt_record_name = TXT_RECORD_NAME
            provider.save()
            print(f"\n✅ Updated CNAME target to: {CLOUDFLARE_CNAME_TARGET}")
        else:
            print(f"\n✓ CNAME target already set correctly")
        
        print("\n📝 SETUP INSTRUCTIONS:")
        print("-" * 70)
        print("""
1. Login to your domain registrar (GoDaddy, Namecheap, etc.)
2. Go to DNS Settings
3. Remove any existing 'www' or 'A' records for this domain
4. Add the CNAME record above
5. Wait for DNS propagation (5-30 minutes)
6. SSL certificate will be auto-generated by Cloudflare

✨ After DNS is set up, your domain will work immediately!
""")
        
        print("\n" + "="*70 + "\n")
    
    # Print quick reference
    print("\n📌 QUICK REFERENCE - CNAME TARGET FOR ALL DOMAINS:")
    print("="*70)
    print(f"All custom domains should point to: {CLOUDFLARE_CNAME_TARGET}")
    print("="*70 + "\n")

if __name__ == "__main__":
    update_cname_records()
