# Generated by Django 4.2.20 on 2025-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_add_hero_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='cname_target',
            field=models.CharField(blank=True, help_text='Unique CNAME target for this provider', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='txt_record_name',
            field=models.CharField(blank=True, help_text='Unique TXT record name for domain verification', max_length=255, null=True),
        ),
    ]
