# Generated by Django 4.2.20 on 2025-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_add_unique_cname_txt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='cloudflare_hostname_id',
            field=models.CharField(blank=True, help_text='Cloudflare Custom Hostname ID for this domain', max_length=100, null=True),
        ),
    ]
