# Generated by Django 4.2.20 on 2025-12-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_add_cloudflare_hostname_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='The actual domain (e.g., salon.com, beauty.example.com)', max_length=255)),
                ('domain_type', models.CharField(choices=[('subdomain', 'Custom Subdomain (e.g., business.nextslot.in)'), ('custom', 'Custom Domain (e.g., www.businessname.com)')], default='subdomain', help_text='Whether this is a subdomain or custom domain', max_length=20)),
                ('dns_record_type', models.CharField(choices=[('cname', 'CNAME Record'), ('a_record', 'A Record'), ('both', 'Both CNAME and A Record')], default='cname', help_text='Type of DNS record(s) to use', max_length=20)),
                ('cname_target', models.CharField(default='app.nextslot.in', help_text='CNAME record target (e.g., app.nextslot.in)', max_length=255)),
                ('a_record_ip', models.CharField(blank=True, help_text='A record IP address (fallback option)', max_length=15, null=True)),
                ('verification_code', models.CharField(help_text='Unique verification code for this domain', max_length=100, unique=True)),
                ('txt_record_name', models.CharField(help_text='TXT record name for domain verification', max_length=255, unique=True)),
                ('ssl_enabled', models.BooleanField(default=False, help_text='Whether SSL/HTTPS is enabled')),
                ('ssl_provider', models.CharField(blank=True, default='lets_encrypt', help_text='SSL certificate provider (e.g., letsencrypt, cloudflare)', max_length=50)),
                ('ssl_certificate_id', models.CharField(blank=True, help_text='Certificate ID from SSL provider', max_length=255, null=True)),
                ('ssl_expiry_date', models.DateField(blank=True, help_text='When the SSL certificate expires', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('dns_configured', 'DNS Configured'), ('dns_verified', 'DNS Verified'), ('ssl_pending', 'SSL Certificate Pending'), ('ssl_active', 'SSL Active'), ('active', 'Active & Live'), ('failed', 'Setup Failed'), ('inactive', 'Inactive')], default='pending', help_text='Current domain setup status', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary/main domain for the provider')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this domain is currently active')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this domain was added')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When domain verification was completed', null=True)),
                ('ssl_generated_at', models.DateTimeField(blank=True, help_text='When SSL certificate was generated', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last successful verification check', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update to this domain record')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this domain setup')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'ordering': ['-is_primary', '-added_at'],
                'indexes': [models.Index(fields=['service_provider', 'is_active'], name='providers_c_service_35a5ac_idx'), models.Index(fields=['status'], name='providers_c_status_8eb9ba_idx'), models.Index(fields=['domain_name'], name='providers_c_domain__6709a3_idx')],
                'unique_together': {('service_provider', 'domain_name')},
            },
        ),
    ]
