# Generated by Django 5.1.15 on 2025-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_customdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to='db_file_storage.urls.get_url'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your business logo (recommended: 500x500px square)', null=True, upload_to='db_file_storage.urls.get_url'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Business logo or profile picture', null=True, upload_to='db_file_storage.urls.get_url'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='db_file_storage.urls.get_url'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to='db_file_storage.urls.get_url'),
        ),
    ]
